services:
  - type: web
    name: yt-dlp-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free
    envVars:
      - key: API_KEY
        value: your-secret-key-2025
